// src/data/vakken.js

// Data bestand gemaakt voor de astro paginas
export const vakken = {
    meesterproef: {
        num: "01",
        titel: "TAVI",
        kortebeschrijving: "TAVI: Toegankelijk Amsterdam Voor Iedereen is een webapp waar gebruikers met een fysieke beperking kunnen zien welke locaties er toegankelijk zijn voor hun.",
        docent: "Victor",
        tijd: "5 weken",
        status: " ",
        introimg: "../images/tavi.png",
        langebeschrijving: "Een online platform creëren waar gebruikers een persoonlijk toegankelijkheidsprofiel instellen en daarna direct kunnen zien welke locaties in Amsterdam goed toegankelijk voor hen zijn, in een lijst én op een kaart. Voor dit platform heb ik de volledige UI/UX ontworpen en gebouwd in Astro. Gebruikers stellen bij binnenkomst een profiel in op basis van hun beperking, waarna ze een gefilterd overzicht zien van Amsterdamse locaties. Elke locatie heeft een detailpagina met een toegankelijkheidsgrid — opgedeeld in beschikbaar, niet beschikbaar en onbekend — met iconen van I Amsterdam. De interface ondersteunt darkmode en high contrast mode, en is mobile-first gebouwd met toegankelijkheid als vertrekpunt.",
        geleerd1: "Data verwerken: Ik heb geleerd hoe ik vanuit andere bestanden data kan verwerken binnen ons prototype. Daarnaast hebben we ook een eigen filtering van de data gemaakt om de 'toegankelijkheid' te bepalen.",
        geleerd2: "Javascript: Ik heb veel geleerd tijdens de workshops van de docenten over Javascript. Daarnaast heb ik geleerd hoe ik in Astro functies kan maken om bijvb dynamische paginas te genereren of een filtering te kunnen maken.",
        geleerd3: "Ontwerpen voor een opdrachtgever: Ik heb geleerd hoe het is om te ontwerpen voor een opdrachtgever en waar je allemaal rekening mee moeten houden tijdens het onwerpen voor iets wat niet misschien jouw smaak is.",
        geleerd4: "Samenwerken: Ik heb geleerd om gestructuureerd en doelgericht samen te werken in teamverband. We hebben onderling duidelijk afspraken gemaakt waardoor dit geleidelijk verliep.",
        link: 'https://tavi-6dj3.onrender.com/'
    },
    sprint0: {
        num: "01",
        vak: "Sprint 0",
        titel: "Xavannah's Board",
        kortebeschrijving: "Een pinterest geinspireerd board waar ik allerlei fotos op heb geplaatst van dingen waar ik affiniteit mee heb. Je hier van alles over mij te weten komen :) ",
        docent: "Sanne t' Hoofd",
        tijd: "8 dagen",
        status: "Ingeleverd",
        introimg: "../images/pinterest.png",
        langebeschrijving: "Ik heb een Pinterest board gemaakt met mijn interesses en dit vertaald naar een persoonlijke website met een Pinterest-achtige, mobile-first responsive grid en…Ik heb een Pinterest board gemaakt met mijn interesses en dit vertaald naar een persoonlijke website met een Pinterest-achtige, mobile-first responsive grid en responsive header. De website heeft de volgende functionaliteiten: light & dark mode (via een :root-tokensysteem), image pop-ups met native HTML dialog-elementen, een API-koppeling die data toont in de dialog bij het klikken op een afbeelding, en een zoek- en filterfunctie (List.js) met contextuele zoekresultaten en gelabelde filters. De styling is aangepast op basis van peer feedback met een eigen kleurenpalet, de CSS is opgeschoond, en de site staat live op GitHub met een bijgewerkte README.",
        geleerd1: "Theming & CSS: via Vasilius geleerd hoe :root gebruikt wordt voor consistente kleuren, border-radius en tekstgroottes — basis voor light/dark mode, later verbeterd na een code review.",
        geleerd2: "Dialogen: pop-ups opgelost met native HTML dialog-elementen, simpeler dan een JS-aanpak (tip van Vasilius).",
        geleerd3: "Zoekfunctie: zoek- en filterfunctionaliteit gebouwd met List.js, met hulp van Sanne werkend gekregen.",
        geleerd4: "Layout: Flexbox vs. Grid en wanneer welke te gebruiken (workshop Cyd), plus mobile-first werken met aangepaste grids voor mobiel/tablet/desktop.",
        link: 'https://xavannahb.github.io/voorstel-website/'
    },
    browsertechnologies: {
        num: "02",
        vak: "Browser Technologies",
        titel: "Erfbelasting NS",
        kortebeschrijving: "Een meerstaps erfbelastingformulier in de huisstijl van de NS, opgebouwd met alleen HTML en CSS, met een progressieve stappenstructuur en real-time gebruikersfeedback via CSS-states.",
        docent: "Vasilis",
        tijd: "18 dagen",
        status: "Ingeleverd",
        introimg: "../images/erfbelasting.png",
        langebeschrijving: "Een meerstaps erfbelastingformulier in de huisstijl van de NS, waarbij de NS-kleuren en typografie zijn vertaald naar CSS-variabelen voor een consistente en on…Een meerstaps erfbelastingformulier in de huisstijl van de NS, waarbij de NS-kleuren en typografie zijn vertaald naar CSS-variabelen voor een consistente en onderhoudbare stijl. Het formulier is opgedeeld in stappen (1a, 1b en 1c), waarbij een volgende stap pas zichtbaar wordt nadat de vorige correct is ingevuld. De gebruiker krijgt gedurende het hele proces feedback: foutmeldingen bij onjuiste invoer, positieve bevestiging bij correcte velden, en doorgaanberichten naar de volgende stap. Dit alles is gebouwd met alleen HTML en CSS — zonder JavaScript.",
        geleerd1: "Ik heb geëxperimenteerd tijdens dit project met HTML formulieren. Zoals de input types (number, tel, date, radio, checkbox), semantische elementen (fieldset, legend, label) en browser-validatie.",
        geleerd2: "Toegankelijkheid: geleerd dat toegankelijkheid begint bij de HTML-structuur, niet bij CSS of JavaScript — correcte koppelingen zorgen ervoor dat het formulier ook begrijpelijk is voor screenreaders.",
        geleerd3: "Huisstijl verwerken: NS-kleuren en typografie vertaald naar CSS-variabelen voor een consistente en onderhoudbare stijl in een andere context.",
        geleerd4: "Gebruikersfeedback: foutmeldingen, positieve validatie en doorgaanberichten toegevoegd via CSS-states (:focus, :valid, :invalid, :user-invalid).",
        link: 'https://xavannahb.github.io/erfbelasting-ns/',
    },
    css: {
        num: "03",
        vak: "CSS",
        titel: "Minecraft Bloem",
        kortebeschrijving: " ",
        docent: "Sanne t' Hoofd",
        tijd: "18 dagen",
        status: "Ingeleverd",
        introimg: "../images/minecraft-bloem.png",
        langebeschrijving: "Ik heb geleerd hoe je 3D-vormen in CSS maakt zonder JavaScript, en hoe je states (zoals kleur of rotatie) puur met :checked en :has() kunt aansturen. Daarnaast heb ik voor het eerst met CSS nesting en @layer gewerkt om mijn CSS te structureren in lagen (reset, tokens, layout, components, themes) — geïnspireerd door Harry Roberts' Inverted Triangle CSS. Dit gaf me veel meer overzicht en hiërarchie in mijn code, iets wat ik nu in vervolgprojecten blijf toepassen.",
        geleerd1: "Kubus maken in CSS: met cube verschillende vlakken tegen elkaar aan gezet en in perspectief gezet met css",
        geleerd2: "Hoe je states (kleur, rotatie, tijd) puur kunt aansturen met :checked en :has()",
        geleerd3: "Hoe CSS nesting werkt en hoe het zorgt voor overzichtelijkere, minder repetitieve code",
        geleerd4: "Hoe je @layer gebruikt om CSS te structureren in lagen (reset, tokens, layout, components, themes), geïnspireerd door Harry Roberts' Inverted Triangle CSS",
        link: 'https://xavannahb.github.io/control-panel-css/',
        
    },
    hackaton: {
        num: "04",
        vak: "Hackaton",
        titel: "Nebula Xplorer",
        kortebeschrijving: "Tijdens de hackathon hebben we aan de slag gegaan met het bouwen van een website voor de Nebula Explorer. In 72 uur heb ik met een groepje van 4 personen een website gebouwd.",
        docent: "Alle docenten",
        tijd: "3 dagen",
        status: "Ingeleverd",
        introimg: "../images/nebula.png",
        langebeschrijving: "Voor dit project heb ik een website gebouwd voor Nebula Xplorer. De Nebula Xplorer is een studentgeleide satellietmissie gericht op röntgenastronomie. We hebben samen in een team van 4 gewerkt aan een nieuwe webpagina voor Nebula. We hebben er als groep voor gekozen om de website wat persoonlijker te maken en vooral alle studenten die aan het project hebben meegeholpen uit te lichten.",
        geleerd1: "Ik heb geleerd hoe je een team verband moet samenwerken onder druk. Hierbij is het essentieel dat er snel keuzes gemaakt worden en dat iemand de leiding hiervoor op zich neemt.",
        geleerd2: " ",
        geleerd3: " ",
        geleerd4: " ",
        link: 'https://xavannahb.github.io/crazy-starships/'
    },
    api: {
        num: "05",
        vak: "API",
        titel: "Amsterdam Horeca Finder",
        kortebeschrijving: "Met de Amsterdam Horeca Finder kan je op basis van je stadsdeel zien welke cafe, kroeg of restaurant bij jou in de buurt is.",
        docent: "Jad",
        tijd: "9 dagen",
        status: "Ingeleverd",
        introimg: "../images/amsterdam-horeca.png",
        langebeschrijving: " ",
        geleerd1: "Ik heb geleerd om met verschillende apis te werken in een ontwerp. Zowel content API's als Web API's. ",
        geleerd2: "Ik heb ook geleerd hoe je in sommige projecten afhankelijk bent van de data die beschikbaar is. Je kan altijd veel ideeën verzinnen maar als de data er niet is om deze vorm te geven dan moet je of een ander idee overwegen of zelf invullind voor data verzinnen.",
        geleerd3: " ",
        geleerd4: " ",
        link: 'https://purple-pulsar.onrender.com/',
    },
    humancomputerinteraction: {
        num: "06",
        vak: "Human Computer Interaction",
        titel: "Audiogram",
        kortebeschrijving: " ",
        docent: "Vasilis",
        tijd: "9 dagen",
        status: "Nog niet afgerond",
        introimg: "../images/audigram.png",
        langebeschrijving: " ",
        geleerd1: " ",
        geleerd2: " ",
        geleerd3: " ",
        geleerd4: " ",
    },

    meesterschap: {
        num: "08",
        vak: "Meesterschap",
        titel: "Meesterschaps Blog",
        kortebeschrijving: " ",
        docent: "Individueel",
        tijd: " dagen",
        status: " ",
        introimg: "../images/meesterschap.png",
        langebeschrijving: "Ik heb deze websit",
        geleerd1: " ",
        geleerd2: " ",
        geleerd3: " ",
        geleerd4: " ",
    },
};